const LANES=[130,280,430];
const BASE={turtle:220,bird:100,wolf:155};
const alive=u=>!u.dead&&u.hp>0;
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const foes=(s,u)=>s.units.filter(v=>v.team!==u.team&&alive(v));
const friends=(s,u)=>s.units.filter(v=>v.team===u.team&&alive(v));
function effect(s,u,text,type='hit'){s.effects.push({x:u.x,y:u.y,text,life:1.15,type});}
function make(id,team,kind,x,y,round,upgrades){let max=BASE[kind]+(team==='enemy'?(round-1)*12:upgrades.filter(x=>x==='vigor').length*20);return {id,team,kind,x,y,hp:max,max,shield:0,cast:0,strike:null,stun:0,cooldown:kind==='bird'?1.3:0,dead:false};}
export function create(round=1,upgrades=[]){round=Math.max(1,Math.min(3,Math.floor(round)||1));let s={phase:'deploy',round,time:0,units:[],effects:[],selectedTarget:null,message:'调整站位，让狰从侧翼突破。',skills:{turtle:0,bird:0,wolf:0},upgrades:[...upgrades],guard:{ally:0,enemy:0}};s.units=[make('a-turtle','ally','turtle',300,280,round,upgrades),make('a-bird','ally','bird',130,280,round,upgrades),make('a-wolf','ally','wolf',220,280,round,upgrades),make('e-turtle','enemy','turtle',650,280,round,[]),make('e-bird','enemy','bird',820,130,round,[]),make('e-last','enemy',round===2?'wolf':'bird',round===2?700:820,430,round,[])];if(round===3)s.units[3].max=s.units[3].hp=280;return s;}
export function deploy(s,id,lane){if(s.phase!=='deploy'||!Number.isInteger(lane)||lane<0||lane>2)return false;const u=s.units.find(u=>u.id===id&&u.team==='ally');if(!u)return false;u.y=LANES[lane];return true;}
export function start(s){if(s.phase!=='deploy')return false;s.phase='battle';s.message='点击敌人指定冲撞目标；在蓄力红圈出现时打断。';return true;}
export function target(s,id){const u=s.units.find(u=>u.id===id&&u.team==='enemy'&&alive(u));if(!u||!['deploy','battle'].includes(s.phase))return false;s.selectedTarget=id;return true;}
function attackTarget(s,u,manual=false){const fs=foes(s,u);if(!fs.length)return null;if(u.kind!=='wolf')return fs.sort((a,b)=>dist(u,a)-dist(u,b))[0];let victim=(manual&&fs.find(x=>x.id===s.selectedTarget))||fs.filter(x=>x.kind==='bird').sort((a,b)=>dist(u,a)-dist(u,b))[0]||fs.sort((a,b)=>dist(u,a)-dist(u,b))[0];const block=fs.find(x=>x.kind==='turtle'&&Math.abs(x.y-u.y)<65&&((u.team==='ally'&&x.x>u.x+10&&x.x<victim.x)||(u.team==='enemy'&&x.x<u.x-10&&x.x>victim.x)));return block||victim;}
function damage(s,source,v,n){if(!alive(v))return;let guard=s.units.find(g=>g.team===v.team&&g.kind==='turtle'&&alive(g)&&g.id!==v.id&&Math.abs(g.y-v.y)<90&&Math.abs(g.x-v.x)<220&&(v.team==='ally'?v.x<g.x:v.x>g.x));if(guard)n*=.55;if(v.shield>0)n*=.25;if(source.team==='ally')n*=1.2**s.upgrades.filter(x=>x==='fang').length;v.hp=Math.max(0,v.hp-n);effect(s,v,`−${Math.round(n)}`);if(v.hp===0){v.dead=true;v.cast=0;v.strike=null;v.stun=0;effect(s,v,'退场','death');}}
export function skill(s,kind){if(s.phase!=='battle'||!(kind in s.skills)||s.skills[kind]>0)return false;const u=s.units.find(u=>u.team==='ally'&&u.kind===kind&&alive(u));if(!u||u.stun>0)return false;const enemy=attackTarget(s,u,true);if(!enemy)return false;s.skills[kind]=({turtle:8,bird:12,wolf:10}[kind])*.8**s.upgrades.filter(x=>x==='focus').length;if(kind==='turtle'){for(const ally of friends(s,u)){ally.shield=2;effect(s,ally,'水幕 · 减伤','shield');}s.message='水幕展开：全队 2 秒内减伤 75%。';}if(kind==='wolf'){u.x=enemy.x+(u.team==='ally'?-42:42);u.y=enemy.y;enemy.stun=1.3;enemy.cast=0;enemy.strike=null;enemy.cooldown=Math.max(enemy.cooldown,1.8);damage(s,u,enemy,48);effect(s,enemy,'冲撞 · 打断','skill');s.message=enemy.kind==='turtle'?'冲撞被玄龟拦住！下局可以调整侧翼站位。':'冲撞命中，打断施法！';}if(kind==='bird'){const chosen=s.units.find(v=>v.id===s.selectedTarget&&v.team==='enemy'&&alive(v))||enemy;for(const v of foes(s,u))if(dist(v,chosen)<125)damage(s,u,v,38);effect(s,chosen,'烈焰爆发','fire');s.message='烈焰命中目标附近的敌人。';}settle(s);return true;}
function settle(s){if(s.phase!=='battle')return;if(!s.units.some(u=>u.team==='enemy'&&alive(u))){s.phase='won';s.message='获胜！你的异兽小队守住了战场。';}else if(!s.units.some(u=>u.team==='ally'&&alive(u))||s.time>=60){s.phase='lost';s.message=s.time>=60?'时间耗尽。调整站位，让狰突破后排再试。':'小队败退。换个站位，或留住技能打断喷火。';}}
export function tick(s,dt){if(s.phase!=='battle'||!Number.isFinite(dt)||dt<=0)return s;dt=Math.min(dt,.1);s.time+=dt;for(const k of Object.keys(s.skills))s.skills[k]=Math.max(0,s.skills[k]-dt);for(const e of s.effects)e.life-=dt;s.effects=s.effects.filter(e=>e.life>0).slice(-50);for(const u of s.units){if(!alive(u))continue;u.shield=Math.max(0,u.shield-dt);u.cooldown=Math.max(0,u.cooldown-dt);u.stun=Math.max(0,u.stun-dt);if(u.stun>0)continue;const v=attackTarget(s,u);if(!v)continue;if(u.cast>0){u.cast-=dt;if(u.cast<=0){for(const victim of foes(s,u))if(dist(victim,u.strike)<95)damage(s,u,victim,u.team==='enemy'?28:18);effect(s,u.strike,'轰！','fire');u.cast=0;u.strike=null;u.cooldown=2.5;}continue;}if(u.kind==='bird'){if(u.cooldown<=0){u.cast=1.3;u.strike={x:v.x,y:v.y};effect(s,u,'喷火蓄力','cast');}continue;}const distance=dist(u,v);if(distance>55){const speed=u.kind==='wolf'?100:25;u.x+=(v.x-u.x)/distance*speed*dt;u.y+=(v.y-u.y)/distance*speed*dt;}else if(u.cooldown<=0){damage(s,u,v,u.kind==='wolf'?13:8);u.cooldown=u.kind==='wolf'?.85:1.25;}}settle(s);return s;}
