import test from 'node:test';
import assert from 'node:assert/strict';
import {create,deploy,start,target,skill,tick} from './arena-engine.mjs';
const unit=(s,id)=>s.units.find(u=>u.id===id);
function play(lane,active){const s=create();deploy(s,'a-wolf',lane);start(s);for(let i=0;i<4000&&s.phase==='battle';i++){tick(s,1/60);if(active&&i%60===0)for(const k of ['turtle','wolf','bird'])skill(s,k);}return s;}
test('deployment accepts only allies and locks when combat begins',()=>{const s=create();assert.equal(deploy(s,'e-turtle',0),false);assert.equal(deploy(s,'a-wolf',0),true);assert.equal(unit(s,'a-wolf').y,130);start(s);assert.equal(deploy(s,'a-wolf',2),false);});
test('explicit target changes flank charge, frontline turtle intercepts center charge',()=>{const s=create();deploy(s,'a-wolf',0);start(s);target(s,'e-last');skill(s,'wolf');assert.equal(unit(s,'e-last').hp,52);assert.equal(unit(s,'e-bird').hp,100);const blocked=create();start(blocked);target(blocked,'e-last');skill(blocked,'wolf');assert.equal(unit(blocked,'e-turtle').hp,172);assert.equal(unit(blocked,'e-last').hp,100);});
test('charge interrupts a pending fire attack and stuns caster',()=>{const s=create();deploy(s,'a-wolf',0);start(s);const bird=unit(s,'e-bird');bird.cast=.3;bird.strike={x:300,y:280};target(s,bird.id);skill(s,'wolf');assert.equal(bird.cast,0);assert.equal(bird.strike,null);assert.ok(bird.stun>0);tick(s,.1);assert.equal(unit(s,'a-turtle').hp,220);});
test('water shield reduces incoming blast damage by three quarters',()=>{function blast(shield){const s=create();start(s);const bird=unit(s,'e-bird');bird.cast=.05;bird.strike={x:300,y:280};if(shield)skill(s,'turtle');tick(s,.1);return 220-unit(s,'a-turtle').hp;}assert.equal(blast(false),28);assert.equal(blast(true),7);});
test('skill cooldown blocks repeated clicks and becomes ready with elapsed time',()=>{const s=create();start(s);assert.equal(skill(s,'bird'),true);const hp=unit(s,'e-turtle').hp;assert.equal(skill(s,'bird'),false);assert.equal(unit(s,'e-turtle').hp,hp);for(let i=0;i<121;i++)tick(s,.1);assert.equal(s.skills.bird,0);});
test('dead units cannot cast and terminal states freeze combat',()=>{const s=create();start(s);unit(s,'a-wolf').hp=0;unit(s,'a-wolf').dead=true;assert.equal(skill(s,'wolf'),false);s.units.filter(u=>u.team==='enemy').forEach(u=>{u.hp=0;u.dead=true;});tick(s,.1);assert.equal(s.phase,'won');const snapshot=JSON.stringify(s);tick(s,.1);assert.equal(skill(s,'bird'),false);assert.equal(JSON.stringify(s),snapshot);});
test('active play wins opening fight; flank positioning preserves wolf, idle squad loses',()=>{const flank=play(0,true),center=play(1,true),idle=play(1,false);assert.equal(flank.phase,'won');assert.equal(center.phase,'won');assert.ok(unit(flank,'a-wolf').hp>0);assert.equal(unit(center,'a-wolf').hp,0);assert.equal(idle.phase,'lost');assert.ok(flank.time<center.time);});
test('evolution upgrades affect health, damage and skill recharge',()=>{const s=create(2,['vigor','fang','focus']);assert.equal(unit(s,'a-wolf').max,175);deploy(s,'a-wolf',0);start(s);target(s,'e-bird');skill(s,'wolf');assert.ok(Math.abs(unit(s,'e-bird').hp-(112-57.6))<.001);assert.equal(s.skills.wolf,8);});
test('a living turtle protects nearby allies positioned behind it',()=>{function hit(behind){const s=create();start(s);const ally=unit(s,'a-bird');ally.x=behind?250:350;const enemy=unit(s,'e-bird');enemy.cast=.05;enemy.strike={x:ally.x,y:ally.y};tick(s,.1);return 100-ally.hp;}assert.equal(hit(false),28);assert.ok(Math.abs(hit(true)-15.4)<.001);});
