import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,start,tickAuto,skill,restoreBattle,battleReport,AUTO_DEFAULTS} from './expedition-engine.mjs';
const unit=(s,id)=>s.units.find(u=>u.id===id);
const play=(s,n=3700)=>{for(let i=0;i<n&&s.phase==='battle';i++)tickAuto(s,1/60);return s;};
test('defaults migrate and idle opening spends no skills',()=>{const s=createBattle({tactics:{wolf:'invalid'}});assert.deepEqual(s.tactics,AUTO_DEFAULTS);start(s);tickAuto(s,1/60);assert.deepEqual(s.skills,{turtle:0,bird:0,wolf:0});assert.equal(s.stats.units['a-wolf'].casts,0);});
test('reactive shields incoming cast while sustain holds for injured ally',()=>{for(const tactic of ['reactive','sustain']){const s=createBattle({tactics:{turtle:tactic}});start(s);Object.assign(unit(s,'e-1'),{cast:.4,strike:{x:130,y:280}});tickAuto(s,1/60);assert.equal(s.stats.units['a-turtle'].casts,tactic==='reactive'?1:0);}const s=createBattle({tactics:{turtle:'sustain'}});start(s);unit(s,'a-bird').hp=40;Object.assign(unit(s,'e-1'),{cast:.4,strike:{x:130,y:280}});tickAuto(s,1/60);assert.equal(s.stats.units['a-turtle'].casts,1);});
test('guard intercepts approaching wolf while flank attacks bird',()=>{const results=[];for(const tactic of ['guard','flank']){const s=createBattle({round:2,tactics:{wolf:tactic}});start(s);Object.assign(unit(s,'a-wolf'),{x:300,y:280});Object.assign(unit(s,'e-0'),{x:190,y:280});Object.assign(unit(s,'e-2'),{x:510,y:280,cast:.5,strike:{x:300,y:280}});s.skills.bird=10;s.skills.turtle=8;tickAuto(s,1/60);results.push({x:unit(s,'a-wolf').x,interrupts:s.stats.units['a-wolf'].interrupts});}assert(results[0].x<200);assert(results[1].x>400);assert.equal(results[1].interrupts,1);});
test('cluster hits largest group while focus follows wolf target',()=>{for(const tactic of ['cluster','focus']){const s=createBattle({tactics:{bird:tactic}});start(s);s.skills.wolf=10;s.skills.turtle=8;Object.assign(unit(s,'a-wolf'),{x:490,y:130});Object.assign(unit(s,'e-0'),{x:600,y:430});Object.assign(unit(s,'e-1'),{x:650,y:130});Object.assign(unit(s,'e-2'),{x:650,y:430});tickAuto(s,1/60);assert.equal(unit(s,'e-1').hp,tactic==='focus'?74:100);assert(unit(s,tactic==='cluster'?'e-2':'e-1').hp<100);}});
test('three beasts need reinforcement against later enemy active skills',()=>{const first=createBattle({lanes:{wolf:0}});start(first);assert.equal(play(first).phase,'won');const second=createBattle({round:2,level:2,owned:{wolf:3,bird:3,turtle:1},lanes:{wolf:0}});start(second);assert.equal(play(second).phase,'lost');});
test('one and two simulation steps per frame produce identical results',()=>{const a=createBattle({lanes:{wolf:0}}),b=createBattle({lanes:{wolf:0}});start(a);start(b);for(let frame=0;frame<300;frame++){tickAuto(a,1/60);tickAuto(a,1/60);}play(b,600);assert.deepEqual(a,b);});
test('snapshot keeps tactics and stats with deterministic continuation',()=>{const run={phase:'battle',tactics:{wolf:'guard',bird:'focus'},round:2};const a=createBattle(run);start(a);play(a,300);const raw=JSON.parse(JSON.stringify(a)),b=restoreBattle(raw,run);assert(b);play(a,60);play(b,60);assert.deepEqual(b,a);raw.stats.units['a-wolf'].damage=-1;assert.equal(restoreBattle(raw,run),null);});
test('old snapshots resume partial recording and reject malformed statistics',()=>{const run={};const s=createBattle(run);start(s);play(s,120);const old=JSON.parse(JSON.stringify(s));delete old.stats;delete old.tactics;delete old.auto;const restored=restoreBattle(old,run);assert(restored);assert.equal(restored.stats.since,s.time);assert(battleReport(restored)[0].fact.startsWith('从第 1 秒恢复记录起'));const bad=JSON.parse(JSON.stringify(s));bad.stats.units['a-wolf'].casts=.5;assert.equal(restoreBattle(bad,run),null);});
test('damage records actual lost health and reports actual interruption counts',()=>{const s=createBattle({});start(s);unit(s,'e-0').hp=5;skill(s,'wolf');assert.equal(s.stats.units['a-wolf'].damage,5);assert.equal(s.stats.units['e-0'].taken,5);assert.match(battleReport(s)[0].fact,/1 次冲撞命中敌方玄龟/);assert(!battleReport(s).some(r=>r.fact.includes('打断敌人')));});

test('guard holds a post near allied bird during opening instead of charging rear',()=>{const s=createBattle({tactics:{wolf:'guard'},lanes:{wolf:0}});start(s);play(s,180);const wolf=unit(s,'a-wolf'),bird=unit(s,'a-bird');assert(Math.abs(wolf.x-bird.x-100)<1);assert(Math.abs(wolf.y-bird.y)<1);assert.equal(s.stats.units['a-wolf'].casts,0);});
