import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,deploy,start,target,skill,tick,restoreBattle} from './expedition-engine.mjs';
import {maxRound} from './progression.mjs';
const ally=(s,k)=>s.units.find(u=>u.id==='a-'+k);
const runBattle=(run,useSkills=true)=>{const s=createBattle(run);start(s);for(let n=0;n<610&&s.phase==='battle';n++){if(useSkills)for(const k of ['wolf','bird','turtle'])skill(s,k);tick(s,.1);}return s;};
test('three and nine copies increase health and damage, level adds health',()=>{const base=createBattle({}),two=createBattle({owned:{wolf:3}}),three=createBattle({owned:{wolf:9},level:4});assert.equal(ally(base,'wolf').max,155);assert.equal(ally(two,'wolf').max,256);assert.equal(ally(two,'wolf').power,1.45);assert.equal(ally(three,'wolf').max,500);assert.equal(ally(three,'wolf').power,2);});
test('deploy rejects invalid lane and cannot reposition after battle begins',()=>{const s=createBattle({});assert.equal(deploy(s,'a-wolf',0),true);assert.equal(ally(s,'wolf').y,130);assert.equal(deploy(s,'a-wolf',3),false);start(s);assert.equal(deploy(s,'a-wolf',2),false);});
test('variant turtle freezes enemies and enables fire synergy',()=>{const s=createBattle({equipped:{turtle:'ice_turtle'}});assert.deepEqual(s.synergies,['fire']);start(s);skill(s,'turtle');assert(s.units.filter(u=>u.team==='enemy').every(u=>u.stun===1));assert.equal(ally(s,'bird').shield,2);});
test('variant bird leaves damaging fire for exactly two seconds',()=>{const s=createBattle({equipped:{bird:'ember_bird'}});start(s);const victim=s.units.find(u=>u.id==='e-1');target(s,victim.id);skill(s,'bird');assert.equal(s.zones.length,1);const hp=victim.hp;tick(s,.1);assert(victim.hp<hp);for(let n=0;n<20;n++)tick(s,.1);assert.equal(s.zones.length,0);});
test('variant wolf bypasses turtle to hit selected rear target',()=>{const base=createBattle({}),variant=createBattle({equipped:{wolf:'shadow_wolf'}});for(const s of [base,variant]){start(s);target(s,'e-1');skill(s,'wolf');}assert(base.units.find(u=>u.id==='e-0').hp<220);assert.equal(variant.units.find(u=>u.id==='e-0').hp,220);assert(variant.units.find(u=>u.id==='e-1').hp<100);});
test('water synergy starts shield; spirit synergy and focus reduce cooldown multiplicatively',()=>{const water=createBattle({equipped:{wolf:'shadow_wolf'}});start(water);assert(water.units.filter(u=>u.team==='ally').every(u=>u.shield===2));const spirit=createBattle({equipped:{bird:'ember_bird'},relics:['focus']});start(spirit);skill(spirit,'bird');assert(Math.abs(spirit.skills.bird-8.448)<1e-9);});
test('relic health, shield duration, flame damage and kill healing have visible effects',()=>{const s=createBattle({relics:['vigor','tide','ember','harvest']});assert.equal(ally(s,'turtle').max,245);start(s);skill(s,'turtle');assert.equal(ally(s,'bird').shield,3);const victim=s.units.find(u=>u.id==='e-1');target(s,victim.id);skill(s,'bird');assert.equal(victim.hp,64);s.skills.bird=0;victim.hp=1;ally(s,'turtle').hp=100;skill(s,'bird');assert.equal(ally(s,'turtle').hp,115);});
test('three-star turtle extends shielding',()=>{const s=createBattle({owned:{turtle:9},relics:['tide']});start(s);skill(s,'turtle');assert.equal(ally(s,'turtle').shield,4);});
test('three upgraded beasts clear four formations while an unupgraded final encounter loses',()=>{for(let round=1;round<=4;round++){const s=runBattle({round,level:Math.min(4,round),owned:{turtle:round>2?3:1,bird:round>1?3:1,wolf:round>1?3:1},lanes:{turtle:1,bird:1,wolf:0},relics:round>2?['fang','focus']:[]});assert.equal(s.phase,'won',`round ${round}`);}assert.equal(runBattle({round:maxRound},false).phase,'lost');});
test('restored battle continues deterministically and rejects damaged state',()=>{const run={round:3,equipped:{bird:'ember_bird'},owned:{bird:3}};const s=createBattle(run);start(s);skill(s,'bird');tick(s,.1);const restored=restoreBattle(JSON.parse(JSON.stringify(s)),run);assert(restored);for(let n=0;n<20;n++){tick(s,.1);tick(restored,.1);}assert.deepEqual(restored,s);for(const mutate of [r=>r.units[0].hp=Infinity,r=>r.units[0].kind='bird',r=>r.units[0].max=99999,r=>r.zones=[{x:100,y:100,radius:999,life:1,sourceId:'a-bird',type:'fire'}],r=>r.phase='won',r=>r.skills.bird=-1]){const bad=JSON.parse(JSON.stringify(s));mutate(bad);assert.equal(restoreBattle(bad,run),null);}});
test('last enemy killed by active skill settles immediately and blocks further skills',()=>{const s=createBattle({});start(s);const enemies=s.units.filter(u=>u.team==='enemy');for(const e of enemies){e.hp=0;e.dead=true;}enemies[1].hp=1;enemies[1].dead=false;target(s,enemies[1].id);skill(s,'bird');assert.equal(s.phase,'won');assert.equal(skill(s,'wolf'),false);});

test('restore requires combat phase consistent with run phase',()=>{const deployState=createBattle({});assert.equal(restoreBattle(deployState,{phase:'battle'}),null);assert(restoreBattle(deployState,{phase:'shop'}));assert(restoreBattle(deployState,{}));const battling=createBattle({});start(battling);assert(restoreBattle(battling,{phase:'battle'}));assert.equal(restoreBattle(battling,{phase:'shop'}),null);const won=runBattle({lanes:{wolf:0}});assert.equal(won.phase,'won');assert(restoreBattle(won,{phase:'battle',lanes:{wolf:0}}));assert.equal(restoreBattle(won,{phase:'shop',lanes:{wolf:0}}),null);});
