import {CARDS,RELICS,createRun,star,buy,reroll,train,equip,begin,settle,chooseRelic,restore,setLane,setTactic,rareChance,roster,placeUnit,removeUnit,sellUnit,sellPrice,GEAR,RACES,buyGear,equipGear,unequipGear,sellGear,sellEgg,itemTier,tierOdds,nextShopXp,maxShopLevel,cardOf,cardName,MUTATIONS,combatStats,maxRound} from './progression.mjs';
import {createBattle,restoreBattle,start,tickAuto as tick,TACTICS,battleReport} from './expedition-engine.mjs';import {portrait} from './eco-art.mjs';
const KEY='shiling.expedition.v1',RECORD='shiling.expedition.record.v1';let run=createRun(),s=createBattle(run),record={runs:0,wins:0,best:0,seen:[]},storageWarning='',paused=false,picked=null,last=0,w=1000,h=560,saveTimer=0,reported=false,speed=2,accumulator=0,lastReport=null,transitioning=false;
try{const old=JSON.parse(localStorage.getItem(KEY)),r=old?.version===1?restore(JSON.stringify(old.run)):null;if(r){speed=old.speed===1?1:2;lastReport=old.lastReport&&Array.isArray(old.lastReport.rows)&&old.lastReport.rows.length<=3&&old.lastReport.rows.every(x=>typeof x.fact==='string'&&typeof x.tip==='string')?old.lastReport:null;run=r;const b=restoreBattle(old.battle,run);if(run.phase==='battle'&&!b){run={...run,phase:'shop',message:'战斗存档无法恢复，已回到本场准备阶段。'};}s=b||createBattle(run);}if(old&&!r)storageWarning='存档无法识别，已开启新旅程。';const rec=JSON.parse(localStorage.getItem(RECORD));if(rec&&Number.isInteger(rec.runs)&&Number.isInteger(rec.wins)&&Number.isInteger(rec.best)&&Array.isArray(rec.seen))record={...rec,seen:rec.seen.filter(id=>CARDS[id]||cardOf(run,id))};}catch{storageWarning='旧存档未能读取，已开启新旅程。';}
if(run.phase==='battle')paused=true;
const cardFilters={ice_turtle:'sepia(.4) saturate(1.6)',ember_bird:'hue-rotate(80deg)',shadow_wolf:'hue-rotate(45deg)',stone_turtle:'grayscale(.8)',moss_turtle:'hue-rotate(35deg) saturate(1.5)',thunder_bird:'hue-rotate(190deg)',sun_bird:'sepia(.6) saturate(1.5)',blood_wolf:'sepia(.7) saturate(2)',moon_wolf:'hue-rotate(70deg) brightness(1.3)'};
const images={},names={turtle:'玄龟',bird:'毕方',wolf:'狰兽'},profiles={turtle:{role:'前排守卫',range:'近战',speed:'慢速',job:'站前排承伤，保护同排后方伙伴。'},bird:{role:'后排术士',range:'远程',speed:'蓄力',job:'站后排输出，惩罚敌方密集站位。'},wolf:{role:'侧翼刺客',range:'近战',speed:'高速',job:'从侧翼切入，打断施法并威胁后排。'}};function imageFor(id,kind){const key=String(id||kind);if(!images[key]){const i=new Image(),svg=portrait(key.startsWith('mut_')?kind:key);i.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg.includes('xmlns=')?svg:svg.replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" '));i.onload=()=>canvas&&draw();images[key]=i;}return images[key];}
const root=document.querySelector('#app');let canvas,ctx,observer;const $=id=>document.getElementById(id);const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const labels={water:'水泽',fire:'烈焰',spirit:'灵契'};
function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,run,battle:s,speed,lastReport}));localStorage.setItem(RECORD,JSON.stringify(record));}catch{storageWarning='保存失败，请勿关闭当前页面。';}}
function playTransition(title,detail,tone='neutral',after=()=>{}){if(transitioning)return;transitioning=true;const layer=document.createElement('div');layer.className=`scene-transition ${tone}`;layer.innerHTML=`<div><span>${esc(title)}</span>${detail?`<small>${esc(detail)}</small>`:''}</div>`;document.body.append(layer);setTimeout(()=>layer.classList.add('show'),20);setTimeout(()=>{layer.classList.add('leave');setTimeout(()=>{layer.remove();transitioning=false;after();},260);},720);}
function bond(){const races={};for(const item of roster(run).filter(u=>run.formation.includes(u.id))){const race=cardOf(run,item.cardId)?.race;(races[race]??=new Set()).add(item.cardId);}const raceText=Object.entries(races).map(([race,ids])=>`${RACES[race]?.name||race} ${ids.size}/2${ids.size>=2?' · '+RACES[race].text:''}`).join('　');const count={};for(const item of roster(run).filter(u=>run.formation.includes(u.id))){const e=cardOf(run,item.cardId)?.element;count[e]=(count[e]||0)+1;}return raceText+'　'+Object.entries(count).map(([e,n])=>`${labels[e]} ${n}/2${n>=2?' · 已激活':''}`).join('　');}
function raceChips(){const deployed=roster(run).filter(u=>run.formation.includes(u.id));return `<div class="race-chips">${Object.entries(RACES).map(([race,r])=>{const count=new Set(deployed.filter(u=>cardOf(run,u.cardId)?.race===race).map(u=>u.cardId)).size;return `<span class="${count>=2?'active':''}" data-tip="${esc(r.text)}">${r.name} ${count}/2</span>`;}).join('')}<small>同族两种异兽激活羁绊</small></div>`;}
function profileText(kind){const p=profiles[kind];return `${p.role} · ${p.range} · ${p.speed}`;}
const roleDetail=kind=>`定位：${profiles[kind]?.job||'根据站位参与自动战斗。'}`;
const statLine=(id,stars=1,loadout={})=>{const st=combatStats(run,id,stars,run.level,loadout);return `生命 ${st.hp} · ${st.attack?`攻 ${st.attack}`:'不攻击'} · 技能 ${st.skillCd}s`;};
const baseStats=id=>{const c=cardOf(run,id),baseId=String(id).startsWith('mut_')&&c?.kind?c.kind:id;return combatStats(run,baseId,1,1,{});};
const currentStats=(id,stars=1,loadout={})=>combatStats(run,id,stars,run.level,loadout);
const statBoosts=(id,stars=1,loadout={})=>{const base=baseStats(id),st=currentStats(id,stars,loadout),hp=st.hp-base.hp,atk=st.attack-base.attack;return {st,hp,atk,boostedHp:hp>0,boostedAtk:atk>0};};
const statBadges=(id,stars=1,loadout={})=>{const {st,boostedHp,boostedAtk}=statBoosts(id,stars,loadout);return `<span class="stat-badges" aria-hidden="true"><b class="stat-badge hp ${boostedHp?'boosted':''}">♥ ${st.hp}</b><b class="stat-badge atk ${boostedAtk?'boosted':''}">⚔ ${st.attack||0}</b></span>`;};
const growthDetail=(id,stars=1,loadout={})=>{const {hp,atk}=statBoosts(id,stars,loadout),parts=[];if(stars>1)parts.push(`${stars}星`);if(run.level>1)parts.push(`商店${run.level}星`);if(loadout.weapon||loadout.skill)parts.push('装备');const c=cardOf(run,id);if(c?.mutation)parts.push(MUTATIONS[c.mutation]?.name||'血脉');return parts.length?`成长：${parts.join(' / ')}｜生命 +${Math.max(0,hp)}｜攻击 +${Math.max(0,atk)}`:'成长：升星、装备和商店等级会继续推高生命 / 攻击。';};
const statDetail=(id,stars=1,loadout={})=>{const st=currentStats(id,stars,loadout);return `数值：生命 ${st.hp}｜${st.attack?`普攻 ${st.attack}/${st.attackCd}s`:'不普攻'}｜移动 ${st.move}\n主动：${st.skillEffect}｜冷却 ${st.skillCd}s\n${growthDetail(id,stars,loadout)}`;};
function offer(o,i){const c=cardOf(run,o.id),n=run.owned[o.id]||0;return `<button class="offer ${c.rarity}" data-buy="${i}" ${o.sold||run.gold<c.cost||n>=9?'disabled':''}><div class="offer-top"><span>${RACES[c.race]?.name||''} · ${c.rarity==='rare'?'稀有':'普通'}</span><b>${c.cost} 金</b></div>${cardArt(c,o.id)}${statBadges(o.id)}<strong>${c.name}</strong><em class="unit-profile">${profileText(c.kind)}${mutationText(c)}</em><small>${c.text}</small><div class="offer-bottom">${o.sold?'已招募':n>=9?'已满星':`招募 · 已有 ${n} / ${n<3?3:9}`}</div></button>`;}
let prepOpen=run.phase==='shop',prepTab='formation',shopType='beast',gearTarget=null,pickedGear=null;
const tierLabel=o=>`${itemTier(o)}星`;
const oddsText=()=>tierOdds(run.level).map((p,i)=>`${i+1}星 ${Math.round(p*100)}%`).join(' · ');
const loadoutText=id=>{const l=run.loadouts?.[id]||{};return [l.weapon&&GEAR[l.weapon].name,l.skill&&GEAR[l.skill].name].filter(Boolean).join(' / ')||'无装备';};
const loadoutDetail=id=>{const l=run.loadouts?.[id]||{},rows=[];if(l.weapon&&GEAR[l.weapon])rows.push(`武器：${GEAR[l.weapon].name}｜${GEAR[l.weapon].text}`);if(l.skill&&GEAR[l.skill])rows.push(`技能：${GEAR[l.skill].name}｜${GEAR[l.skill].text}`);return rows.length?rows.join('\n'):'装备：无';};
const artStyle=c=>Number.isInteger(c?.hue)?` style="filter:hue-rotate(${c.hue}deg) saturate(1.28)"`:'';
const artClass=(base,id)=>`${base} ${String(id||'').startsWith('mut_')?'mutant':id||''}`;
const cardArt=(c,id,base='offer-art')=>`<div class="${artClass(base,id)}"${artStyle(c)}>${portrait(String(id||'').startsWith('mut_')?c.kind:id||c.kind)}</div>`;
const unitArt=(item,base='slot-art')=>cardArt(cardOf(run,item.cardId)||{kind:item.kind},item.cardId,base);
const mutationText=c=>c?.mutation&&MUTATIONS[c.mutation]?` · ${MUTATIONS[c.mutation].name}`:'';
const rarityText=c=>c?.rarity==='rare'?'稀有':'普通';
const tipAttr=text=>text?` data-tip="${esc(text)}"`:'';
const traitText=c=>({
  armor:'特性：减伤坦克，适合吃近战火力。',
  regen:'特性：自我回复，拖长战斗更赚。',
  quickcast:'特性：施法更快，更依赖主动技循环。',
  power:'特性：稳定增伤，适合堆输出装备。',
  leech:'特性：吸血续航，越能打越能活。',
  ward:'特性：开局短盾，抗第一波爆发。',
  pacifist:'特性：不普攻，改为周期治疗队友。',
  sniper:'特性：普攻变为蓄力单点狙击。',
  deathrattle:'特性：遗言护盾，死亡后保护全队。',
  death_summon:'特性：遗言召唤，倒下后留下幼魇继续作战。',
  summoner:'特性：主动技变为召唤，用数量压住战线。',
  team_heal:'特性：主动技变为群体治疗，保护低血队友。',
  growth:'特性：战斗越久，全队生命上限越高。',
  thorns:'特性：反刺近战，惩罚贴脸攻击者。',
  chain:'特性：主动技变为雷链，适合打分散敌人。',
  rally:'特性：在场鼓舞，全队伤害提高。',
  curse:'特性：命中虚弱，削弱敌方输出。',
  taunt:'特性：嘲讽前排，吸引附近敌方火力保护后排。'
})[c?.passive]||'';
const cardDetail=(subject,stars=1,loadout={})=>{const id=typeof subject==='string'?subject:subject?.id||Object.entries(CARDS).find(([,card])=>card===subject)?.[0],c=typeof subject==='string'?cardOf(run,subject):subject;if(!c)return '';const statId=id||c.id||c.kind,trait=traitText(c);return `${c.name}｜${RACES[c.race]?.name||c.race}｜${labels[c.element]||c.element}｜${rarityText(c)}｜${c.cost}金
${roleDetail(c.kind)}${mutationText(c)}
${statDetail(statId,stars,loadout)}${trait?`
${trait}`:''}${c.mutation&&MUTATIONS[c.mutation]?`
血脉：${MUTATIONS[c.mutation].text}`:''}`;};
const gearDetail=id=>{const g=GEAR[id];return `${g.name}｜${g.type==='weapon'?'武器':'技能'}｜${g.cost}金\n${g.text}`;};
const equippedGearDetail=(unitId,type)=>{const id=run.loadouts?.[unitId]?.[type];return id?`${gearDetail(id)}\n点按：卸回手牌区。\n拖动：放到其他伙伴身上换装，放到招募区卖掉。`:'';};
const equippedChips=item=>{const l=run.loadouts?.[item.id]||{},rows=[];for(const type of ['weapon','skill']){const id=l[type],g=GEAR[id];if(g)rows.push(`<span class="equipped-chip ${type}" data-equipped-gear="${esc(item.id)}" data-gear-type="${type}" data-tip="${esc(equippedGearDetail(item.id,type))}">${type==='weapon'?'⚔':'✦'}${esc(g.name)}</span>`);}return rows.length?`<span class="equipped-chips">${rows.join('')}</span>`:'';};
const offerDetail=o=>o.type==='egg'?`山海胚胎｜4金\n购买后不会立刻上阵，第 ${run.round+1} 战备战时自动孵化一只随机异兽。`:o.type==='gear'?gearDetail(o.id):cardDetail(o.id);
const prepScrollState=()=>{const d=$('prep-dialog'),b=d?.querySelector('.prep-layout');return d?.open?{dialog:d.scrollTop||0,body:b?.scrollTop||0,x:window.scrollX||0,y:window.scrollY||0}:null;};
function restorePrepScrollState(state){if(!state)return;const apply=()=>{const d=$('prep-dialog'),b=d?.querySelector('.prep-layout');if(b)b.scrollTop=state.body;if(d)d.scrollTop=state.dialog;window.scrollTo(state.x,state.y);};apply();requestAnimationFrame(apply);setTimeout(apply,0);}
const unitDetail=item=>`${cardDetail(item.cardId,item.stars,run.loadouts?.[item.id]||{})}\n星级：${item.stars}星\n${loadoutDetail(item.id)}\n出售：${sellPrice(item,run)}金`;
const inspector=(findItem)=>{const unit=picked&&findItem(picked);if(unit)return unitDetail(unit).replace(/\n/g,' · ');if(pickedGear!==null&&run.gearBag?.[pickedGear])return gearDetail(run.gearBag[pickedGear]).replace(/\n/g,' · ');return '点选或悬浮卡牌查看属性 / 技能 / 羁绊';};
const occurrenceKey=(prefix,identity,counts)=>{const key=`${prefix}:${identity}`,count=counts.get(key)||0;counts.set(key,count+1);return `${key}:${count}`;};
const keyedHandEntries=entries=>{const gearCounts=new Map(),eggCounts=new Map();return entries.map((e,natural)=>({...e,natural,key:e.type==='unit'?`unit:${e.item.id}`:e.type==='gear'?occurrenceKey('gear',e.id,gearCounts):occurrenceKey('egg',`${e.egg.tier}:${e.egg.readyRound}`,eggCounts)}));};
const orderedHandEntries=items=>{const field=new Set(run.formation||[]),entries=[...items.filter(u=>!field.has(u.id)).map(item=>({type:'unit',item})),...(run.gearBag||[]).map((id,index)=>({type:'gear',id,index})),...(run.pendingEggs||[]).map((egg,index)=>({type:'egg',egg,index}))],order=run.handOrder||[];return keyedHandEntries(entries).sort((a,b)=>{const ai=order.indexOf(a.key),bi=order.indexOf(b.key);return (ai<0?9999+a.natural:ai)-(bi<0?9999+b.natural:bi);});};
const formationPower=items=>{const byId=Object.fromEntries(items.map(u=>[u.id,u])),total=(run.formation||[]).reduce((sum,id)=>{const u=byId[id];if(!u)return sum;const st=currentStats(u.cardId,u.stars,run.loadouts?.[u.id]||{});sum.hp+=st.hp;sum.atk+=st.attack||0;return sum;},{hp:0,atk:0});return `总血 ${total.hp} · 总攻 ${total.atk}`;};
const handCard=e=>e.type==='unit'?`<button data-unit="${e.item.id}" class="roster-card ${picked===e.item.id?'selected':''}"${tipAttr(unitDetail(e.item))}><span${artStyle(cardOf(run,e.item.cardId))}>${portrait(String(e.item.cardId).startsWith('mut_')?e.item.kind:e.item.cardId)}</span>${statBadges(e.item.cardId,e.item.stars,run.loadouts?.[e.item.id]||{})}<div><strong>${cardName(run,e.item.cardId)} ${'★'.repeat(e.item.stars)}</strong><small>${statLine(e.item.cardId,e.item.stars,run.loadouts?.[e.item.id]||{})}</small><em>${loadoutText(e.item.id)}</em></div></button>`:e.type==='gear'?`<button data-gear="${e.index}" class="gear-card ${pickedGear===e.index?'selected':''}"${tipAttr(gearDetail(e.id))}><span>${GEAR[e.id].type==='weapon'?'⚔':'✦'}</span><strong>${GEAR[e.id].name}</strong><small>${GEAR[e.id].type==='weapon'?'武器':'技能'} · ${GEAR[e.id].text}</small></button>`:`<button class="gear-card egg-card" data-pending-egg="${e.index}"${tipAttr(`山海胚胎｜${e.egg.tier}星
第 ${e.egg.readyRound} 战备战时自动孵化。
拖到招募区可卖 2 金。`)}><span>卵</span><strong>山海胚胎</strong><small>第 ${e.egg.readyRound} 战孵化</small></button>`;
function shopOffer(o,i){
  if(o.type==='egg'){return `<button class="offer egg-offer ${o.sold?'sold':''}" data-buy="${i}" data-offer-drag="${i}"${tipAttr(offerDetail(o))} ${o.sold||run.gold<4||run.round>=maxRound?'disabled':''}><div class="offer-top"><span>山海胚胎 · ${tierLabel(o)}</span><b>4 金</b></div><div class="egg-symbol">卵</div><strong>孵化异兽</strong><em class="unit-profile">延迟收益 · 下场孵化</em><small>下场备战孵化，随机职业 / 血脉 / 外观。</small><div class="offer-bottom">${o.sold?'已购入':run.round>=maxRound?'末战不再孵化':`购买 · 第 ${run.round+1} 战孵化`}</div></button>`;}
  if(o.type==='gear'){
    const c=GEAR[o.id],kind=c.type==='weapon'?'武器':'技能';
    return `<button class="offer gear-offer ${o.sold?'sold':''}" data-buy="${i}" data-offer-drag="${i}"${tipAttr(offerDetail(o))} ${o.sold||run.gold<c.cost?'disabled':''}><div class="offer-top"><span>${kind} · ${tierLabel(o)}</span><b>${c.cost} 金</b></div><div class="gear-symbol">${c.type==='weapon'?'⚔':'✦'}</div><strong>${c.name}</strong><small>${c.text}</small><div class="offer-bottom">${o.sold?'已购买':'点按购买 · 可拖到手牌'}</div></button>`;
  }
  const c=cardOf(run,o.id),n=run.owned[o.id]||0;
  return `<button class="offer ${c.rarity} ${String(o.id).startsWith('mut_')?'mutant-offer':''}" data-buy="${i}" data-offer-drag="${i}"${tipAttr(offerDetail(o))} ${o.sold||run.gold<c.cost||n>=9?'disabled':''}><div class="offer-top"><span>${RACES[c.race]?.name||''} · ${tierLabel(o)}</span><b>${c.cost} 金</b></div>${cardArt(c,o.id)}${statBadges(o.id)}<strong>${c.name}</strong><em class="unit-profile">${statLine(o.id)}</em><small>${c.text}</small><div class="offer-bottom">${o.sold?'已招募':n>=9?'已满星':`购买 · 已有 ${n}/9`}</div></button>`;
}
function shell(){const scrollState=prepScrollState();observer?.disconnect();const items=roster(run),findItem=id=>items.find(u=>u.id===id);if(picked&&!findItem(picked))picked=null;if(pickedGear!==null&&(!run.gearBag||pickedGear>=run.gearBag.length))pickedGear=null;if(!findItem(gearTarget))gearTarget=items[0]?.id||null;const xpNeed=nextShopXp(run.level),quickInfo=inspector(findItem);root.innerHTML=`<header><div class="brand">食灵<span>列传</span></div><div class="header-right"><button id="speed" class="quiet">${speed}×</button><button id="pause" class="quiet" ${run.phase!=='battle'?'hidden':''}>${paused?'继续':'暂停'}</button><button id="reset" class="quiet">新旅程</button></div></header><main><section class="match-bar"><strong>第 ${run.round} / ${maxRound} 战</strong><span>${run.gold} 金 · 商店 ${run.level}星</span><span class="lives">${'♥'.repeat(run.lives)}</span></section><section class="battle-heading"><span>我方 ${run.formation.filter(Boolean).length} / 6</span><span id="time"></span><span>敌方 ${s.units.filter(u=>u.team==='enemy').length} 兽 · 最高 ${Math.max(...s.units.filter(u=>u.team==='enemy').map(u=>u.stars||1))} 星</span></section><section class="arena"><canvas aria-label="异兽自动战场"></canvas><div id="overlay" hidden></div></section><div class="play-bar"><p id="status" role="status"></p>${run.phase==='shop'?'<button id="open-prep" class="start">备战 / 出战 →</button>':'<span class="auto-label">自动交战</span>'}</div><details class="match-details"><summary>羁绊、遗物与上场复盘</summary><p>${bond()}</p><p>${run.relics.map(id=>RELICS[id].name).join(' · ')||'胜利后获得遗物'}</p>${lastReport?lastReport.rows.map(r=>`<p>${esc(r.fact)}<br><small>${esc(r.tip)}</small></p>`).join(''):''}</details><footer>${storageWarning||'本机自动保存'}</footer></main>${run.phase==='shop'?`<dialog id="prep-dialog" aria-labelledby="prep-title"><div class="prep-head"><strong id="prep-title">第 ${run.round} 战 · 备战</strong><span>${run.gold} 金 · 经验 ${run.xp}${run.level<maxShopLevel?`/${xpNeed}`:' · 满星'}</span><button id="close-prep" aria-label="关闭备战">✕</button></div><div class="prep-body prep-layout">
<section id="shop-zone" class="prep-zone shop-zone"><div class="zone-title"><b>招募区</b><div class="shop-actions"><button data-shop="reroll" ${run.gold<1?'disabled':''}>刷新 1 金</button><button data-shop="train" ${run.level>=maxShopLevel||run.xp+run.gold<xpNeed?'disabled':''}>${run.level>=maxShopLevel?'满星':run.xp>=xpNeed?'自动升级':`升级 补${xpNeed-run.xp}金`}</button></div></div><div class="offers">${run.shop.map(shopOffer).join('')}</div></section>
<section class="prep-zone formation-zone"><div class="zone-title"><b>布阵区</b><span>${formationPower(items)}</span></div>${raceChips()}<div class="grid-label"><span>后排</span><span>前排 →</span></div><div id="formation-slots">${run.formation.map((id,index)=>{const item=findItem(id);return `<button class="formation-slot ${item?'occupied':''} ${picked===id&&id?'selected':''}" data-slot="${index}" ${item?`data-unit-drag="${id}"`:''}${item?tipAttr(unitDetail(item)):''} aria-label="${slotName(index)} ${item?cardName(run,item.cardId):'空格'}">${item?`${unitArt(item,'slot-art')}${statBadges(item.cardId,item.stars,run.loadouts?.[item.id]||{})}<b>${cardName(run,item.cardId)} ${'★'.repeat(item.stars)}</b><em>${profileText(item.kind)}${mutationText(cardOf(run,item.cardId))}</em><small>${loadoutText(item.id)}</small>${equippedChips(item)}`:'<strong class="empty-slot">＋</strong><small>空位</small>'}</button>`;}).join('')}</div></section>
<section id="hand-zone" class="prep-zone hand-zone"><div class="zone-title"><b>手牌区</b></div><div class="hand-list">${orderedHandEntries(items).map(handCard).join('')||'<p class="empty-bench">从招募区购买卡牌<br>最多六只伙伴出阵</p>'}</div></section>
<details class="tactic-panel"><summary>自动战术</summary><p class="prep-hint">选好后自动执行，不用点击技能</p><div class="tactic-options">${['turtle','wolf','bird'].map(k=>`<div><b>${names[k]}</b><div>${TACTICS[k].map(t=>`<button data-tactic="${k}" data-value="${t.id}" class="${run.tactics[k]===t.id?'active':''}">${t.label}</button>`).join('')}</div><small>${TACTICS[k].find(t=>t.id===run.tactics[k])?.description||''}</small></div>`).join('')}</div></details>
</div><div class="prep-foot"><span class="quick-inspector">${esc(quickInfo)}</span><button class="start" id="start" ${!run.formation.some(Boolean)?'disabled':''}>出战 →</button></div></dialog>`:''}`;
canvas=root.querySelector('canvas');ctx=canvas.getContext('2d');observer=new ResizeObserver(resize);observer.observe(canvas);resize();ui();draw();showPanel();const dialog=$('prep-dialog');if(dialog){dialog.addEventListener('cancel',()=>{prepOpen=false;picked=null;pickedGear=null;});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom){prepOpen=false;dialog.close();}}});if(prepOpen)dialog.showModal();restorePrepScrollState(scrollState);}}
function ui(){if(!$('time'))return;$('time').textContent=s.phase==='deploy'?'待出战':Math.max(0,60-Math.floor(s.time))+' 秒';$('status').textContent=run.phase==='battle'?'战术自动执行中':run.phase==='shop'?'招募、布阵，然后出战':run.message;}
function showPanel(){const o=$('overlay');if(run.phase==='reward'){o.hidden=false;o.innerHTML=`<span class="eyebrow">胜利 · 招募资金已到账</span><h2>带走一件遗物</h2><div class="upgrades">${run.rewards.map(id=>`<button data-relic="${id}">${RELICS[id].name}<small>${RELICS[id].text}</small></button>`).join('')}</div>`;}else if(['won','lost'].includes(run.phase)){o.hidden=false;o.innerHTML=`<span class="eyebrow">旅程结束 · ${run.wins} 胜</span><h2>${run.phase==='won'?'山海之主':'下一次，换一种阵容'}</h2><p>你的图鉴与最佳记录已保留。本次升星和金币属于这段旅程。</p><button data-new>开启新旅程</button>`;}else if(paused){o.hidden=false;o.innerHTML='<h2>战场已暂停</h2><button data-resume>继续</button>';}else{o.hidden=true;o.replaceChildren();}}
function commit(next,opts={}){if(next===run)return;const previousPhase=run.phase;const apply=()=>{run=next;if(run.phase==='shop'){s=createBattle(run);if(previousPhase!=='shop'){prepOpen=true;prepTab='formation';}}save();shell();};if(opts.transition)playTransition(opts.transition.title,opts.transition.detail,opts.transition.tone,apply);else apply();}
function finish(){if(transitioning||run.phase!=='battle'||!['won','lost'].includes(s.phase))return;lastReport={won:s.phase==='won',round:run.round,rows:battleReport(s)};const won=s.phase==='won',round=run.round,terminal=round===maxRound||(!won&&run.lives<=1),detail=terminal?(won?'十战完成，查看旅程结果':'旅程结束，查看本局记录'):(won?'选择遗物，准备下一战':'结算资源，调整阵容');playTransition(won?'胜利':'失利',detail,won?'win':'lose',()=>{run=settle(run,won);record.best=Math.max(record.best,lastReport.round);if(['won','lost'].includes(run.phase)&&!reported){record.runs++;if(run.phase==='won')record.wins++;reported=true;}if(run.phase==='shop'){s=createBattle(run);prepOpen=true;prepTab='formation';}if(run.phase==='reward')prepOpen=false;if(['won','lost'].includes(run.phase))prepOpen=false;run.message=run.message||`第 ${round} 战结束。`;save();shell();});}
function pause(){if(run.phase!=='battle')return;paused=!paused;$('pause').textContent=paused?'继续':'暂停';ui();showPanel();save();}
function buyOffer(index){const offer=run.shop[index],next=buy(run,index);if(next!==run){if(offer?.type==='beast')record.seen=[...new Set([...record.seen,offer.id])];}commit(next);return next;}
function buyOfferToSlot(index,slot){const before=run,offer=before.shop[index],next=buy(before,index);if(next===before)return;if(offer?.type==='beast'){record.seen=[...new Set([...record.seen,offer.id])];const units=roster(next).filter(u=>u.cardId===offer.id),unit=units[units.length-1];commit(unit?placeUnit(next,unit.id,slot):next);return;}if(offer?.type==='gear'){const occupant=next.formation?.[slot];commit(occupant?equipGear(next,(next.gearBag||[]).length-1,occupant):next);return;}commit(next);}
root.addEventListener('click',e=>{if(performance.now()<ignoreClickUntil)return;const chip=e.target.closest('[data-equipped-gear]');if(chip){e.preventDefault();e.stopPropagation();commit(unequipGear(run,chip.dataset.equippedGear,chip.dataset.gearType));picked=null;pickedGear=null;return;}const b=e.target.closest('button');if(!b||b.disabled)return;if($('prep-dialog')?.contains(b)){e.preventDefault();b.blur();}if(b.id==='open-prep'){prepOpen=true;shell();return;}if(b.id==='close-prep'){prepOpen=false;picked=null;pickedGear=null;$('prep-dialog').close();return;}if(b.id==='reset'||b.hasAttribute('data-new')){if(['won','lost'].includes(run.phase)||confirm('开始新旅程？本局金币、经验与升星将重置，图鉴保留。')){playTransition('新旅程','重新招募第一支异兽小队','reward',()=>{run=createRun();s=createBattle(run);prepOpen=true;prepTab='formation';reported=false;paused=false;lastReport=null;accumulator=0;picked=null;pickedGear=null;save();shell();});}return;}if(b.id==='speed'){speed=speed===1?2:1;$('speed').textContent=speed+'× 速度';save();return;}if(b.dataset.tactic){commit(setTactic(run,b.dataset.tactic,b.dataset.value));return;}if(b.id==='pause'||b.hasAttribute('data-resume')){pause();return;}if(b.dataset.buy!==undefined){buyOffer(Number(b.dataset.buy));return;}if(b.dataset.shop==='reroll'){commit(reroll(run));return;}if(b.dataset.shop==='train'){commit(train(run));return;}if(b.dataset.unit){picked=b.dataset.unit;pickedGear=null;shell();return;}if(b.dataset.gear!==undefined){pickedGear=Number(b.dataset.gear);picked=null;shell();return;}if(b.dataset.slot!==undefined){const index=Number(b.dataset.slot),occupant=run.formation[index];if(pickedGear!==null&&occupant){commit(equipGear(run,pickedGear,occupant));pickedGear=null;return;}if(picked){commit(placeUnit(run,picked,index));}else{picked=occupant;pickedGear=null;shell();}return;}if(b.dataset.relic){const relic=RELICS[b.dataset.relic]?.name||'遗物';commit(chooseRelic(run,b.dataset.relic),{transition:{title:`${relic}入队`,detail:`第 ${Math.min(maxRound,run.round+1)} 战备战`,tone:'reward'}});return;}if(b.id==='start'){const next=begin(run);if(next===run)return;playTransition(`第 ${run.round} 战`, '异兽入场，自动交战', 'battle',()=>{run=next;start(s);prepOpen=false;paused=false;picked=null;pickedGear=null;save();shell();});}});
let dragState=null,ignoreClickUntil=0;
function clearDrag(){document.querySelector('.unit-drag-ghost')?.remove();root.querySelectorAll('.drop-hover,.dragging').forEach(n=>n.classList.remove('drop-hover','dragging'));dragState=null;}
function dragGhostHTML(state){if(state.type==='offer'){const o=run.shop[state.index];if(o?.type==='gear')return `<div class="gear-symbol">${GEAR[o.id].type==='weapon'?'⚔':'✦'}</div>`;if(o?.type==='egg')return '<div class="egg-symbol">卵</div>';const c=cardOf(run,o?.id);return c?portrait(c.kind):'';}if(state.type==='gear'){const id=run.gearBag[state.index];return `<div class="gear-symbol">${GEAR[id].type==='weapon'?'⚔':'✦'}</div>`;}if(state.type==='equippedGear'){const id=run.loadouts?.[state.unitId]?.[state.gearType];return id?`<div class="gear-symbol">${GEAR[id].type==='weapon'?'⚔':'✦'}</div>`:'';}if(state.type==='egg')return '<div class="egg-symbol">卵</div>';const item=roster(run).find(u=>u.id===state.id);return item?portrait(item.kind):'';}
root.addEventListener('dragstart',e=>e.preventDefault());
root.addEventListener('pointerdown',e=>{if(run.phase!=='shop'||e.button!==0)return;const el=e.target.closest('[data-equipped-gear],[data-pending-egg],[data-unit],[data-unit-drag],[data-offer-drag],[data-gear]');if(!el)return;if(el.dataset.equippedGear!==undefined)dragState={type:'equippedGear',unitId:el.dataset.equippedGear,gearType:el.dataset.gearType,x:e.clientX,y:e.clientY,pointerId:e.pointerId,active:false};else if(el.dataset.pendingEgg!==undefined)dragState={type:'egg',index:Number(el.dataset.pendingEgg),x:e.clientX,y:e.clientY,pointerId:e.pointerId,active:false};else if(el.dataset.offerDrag!==undefined)dragState={type:'offer',index:Number(el.dataset.offerDrag),x:e.clientX,y:e.clientY,pointerId:e.pointerId,active:false};else if(el.dataset.gear!==undefined)dragState={type:'gear',index:Number(el.dataset.gear),x:e.clientX,y:e.clientY,pointerId:e.pointerId,active:false};else dragState={type:'unit',id:el.dataset.unit||el.dataset.unitDrag,x:e.clientX,y:e.clientY,pointerId:e.pointerId,active:false};});
root.addEventListener('pointermove',e=>{if(!dragState||e.pointerId!==dragState.pointerId)return;if(!dragState.active&&Math.hypot(e.clientX-dragState.x,e.clientY-dragState.y)<6)return;e.preventDefault();if(!dragState.active){dragState.active=true;root.setPointerCapture(e.pointerId);const ghost=document.createElement('div');ghost.className='unit-drag-ghost';ghost.innerHTML=dragGhostHTML(dragState);$('prep-dialog').append(ghost);$('formation-slots')?.classList.add('dragging');}const ghost=document.querySelector('.unit-drag-ghost');ghost.style.left=(e.clientX-35)+'px';ghost.style.top=(e.clientY-40)+'px';root.querySelectorAll('.drop-hover').forEach(n=>n.classList.remove('drop-hover'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot],#hand-zone,#shop-zone')?.classList.add('drop-hover');if(e.clientY<45)window.scrollBy(0,-18);else if(e.clientY>innerHeight-45)window.scrollBy(0,18);});
root.addEventListener('pointerup',e=>{if(!dragState||e.pointerId!==dragState.pointerId)return;const state=dragState,zone=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot],#hand-zone,#shop-zone');if(root.hasPointerCapture(e.pointerId))root.releasePointerCapture(e.pointerId);clearDrag();if(!state.active)return;ignoreClickUntil=performance.now()+250;e.preventDefault();if(run.phase!=='shop'||!zone)return;if(state.type==='offer'){if(zone.id==='hand-zone')buyOffer(state.index);else if(zone.dataset.slot!==undefined)buyOfferToSlot(state.index,Number(zone.dataset.slot));return;}if(state.type==='gear'){if(zone.id==='shop-zone')commit(sellGear(run,state.index));else if(zone.dataset.slot!==undefined){const occupant=run.formation[Number(zone.dataset.slot)];if(occupant)commit(equipGear(run,state.index,occupant));}return;}if(state.type==='equippedGear'){const n=unequipGear(run,state.unitId,state.gearType),last=(n.gearBag||[]).length-1;if(n===run||last<0)return;if(zone.id==='hand-zone')commit(n);else if(zone.id==='shop-zone')commit(sellGear(n,last));else if(zone.dataset.slot!==undefined){const occupant=n.formation[Number(zone.dataset.slot)];if(occupant)commit(equipGear(n,last,occupant));}return;}if(state.type==='egg'){if(zone.id==='shop-zone')commit(sellEgg(run,state.index));return;}if(state.type==='unit'){if(zone.id==='shop-zone')commit(sellUnit(run,state.id));else if(zone.id==='hand-zone')commit(removeUnit(run,run.formation.indexOf(state.id)));else commit(placeUnit(run,state.id,Number(zone.dataset.slot)));}});
root.addEventListener('pointercancel',clearDrag);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&run.phase==='battle'&&!paused)pause();});addEventListener('blur',()=>{if(run.phase==='battle'&&!paused)pause();});addEventListener('pagehide',save);
const hoverTip=document.createElement('div');hoverTip.className='card-tip';hoverTip.hidden=true;document.body.append(hoverTip);function moveTip(e){hoverTip.style.left=Math.min(innerWidth-24,Math.max(12,e.clientX+16))+'px';hoverTip.style.top=Math.min(innerHeight-24,Math.max(12,e.clientY+16))+'px';}root.addEventListener('pointerover',e=>{const el=e.target.closest('[data-tip]');if(!el||matchMedia('(max-width:520px)').matches)return;const dialog=$('prep-dialog');if(dialog?.open&&hoverTip.parentElement!==dialog)dialog.append(hoverTip);else if(!dialog?.open&&hoverTip.parentElement!==document.body)document.body.append(hoverTip);hoverTip.textContent=el.dataset.tip;hoverTip.hidden=false;moveTip(e);});root.addEventListener('pointermove',e=>{if(!hoverTip.hidden)moveTip(e);});root.addEventListener('pointerout',e=>{if(e.target.closest('[data-tip]')&&!e.relatedTarget?.closest('[data-tip]'))hoverTip.hidden=true;});root.addEventListener('focusin',e=>{const el=e.target.closest('[data-tip]');if(!el||matchMedia('(max-width:520px)').matches)return;hoverTip.textContent=el.dataset.tip;hoverTip.hidden=false;const r=el.getBoundingClientRect();moveTip({clientX:r.right,clientY:r.top});});root.addEventListener('focusout',()=>hoverTip.hidden=true);

function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='#102a25';ctx.fillRect(0,0,w,h);const z=Math.min(w/1000,h/560);ctx.save();ctx.translate((w-z*1000)/2,(h-z*560)/2);ctx.scale(z,z);const gradient=ctx.createLinearGradient(0,0,1000,560);gradient.addColorStop(0,'#243a46');gradient.addColorStop(.48,'#273f34');gradient.addColorStop(1,'#102b26');ctx.fillStyle=gradient;ctx.fillRect(0,0,1000,560);
const map=p=>({x:p.x,y:p.y});
const drawAt=(p,team,fn)=>{const q=map(p);ctx.save();ctx.translate(q.x,q.y);fn(q);ctx.restore();return q;};
for(let i=0;i<80;i++){let x=(i*173+21)%1000,y=(i*97+35)%560;ctx.strokeStyle='#78956a20';ctx.beginPath();ctx.moveTo(x-3,y+4);ctx.lineTo(x,y-3);ctx.lineTo(x+3,y+3);ctx.stroke();}for(const y of [130,280,430]){ctx.strokeStyle='#c9d2a61c';ctx.setLineDash([5,12]);ctx.beginPath();ctx.moveTo(70,y);ctx.lineTo(930,y);ctx.stroke();}ctx.setLineDash([]);ctx.strokeStyle='#d3bb7328';ctx.beginPath();ctx.moveTo(500,48);ctx.lineTo(500,512);ctx.stroke();ctx.fillStyle='#a1b68a30';ctx.font='54px serif';ctx.textAlign='center';ctx.fillText('我',115,300);ctx.fillText('敌',885,300);
for(const zone of s.zones||[]){const q=map(zone);ctx.fillStyle='#d8833940';ctx.strokeStyle='#e4a95b';ctx.beginPath();ctx.arc(q.x,q.y,zone.radius*.72,0,Math.PI*2);ctx.fill();ctx.stroke();}
for(const u of s.units){if(u.dead||u.hp<=0)continue;if(u.cast>0&&u.strike){const q=map(u.strike);ctx.fillStyle=u.team==='enemy'?'#dd6e4440':'#69aec840';ctx.strokeStyle=u.team==='enemy'?'#e29d68':'#95cede';ctx.beginPath();ctx.arc(q.x,q.y,60,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='12px sans-serif';ctx.fillStyle='#ffe1a1';const me=map(u,u.team);ctx.fillText('蓄力',me.x,me.y-63);}}
for(const u of [...s.units].sort((a,b)=>a.y-b.y||a.x-b.x)){const q=map(u);if(u.dead||u.hp<=0){ctx.fillStyle='#14291f55';ctx.beginPath();ctx.ellipse(q.x,q.y+15,25,9,0,0,Math.PI*2);ctx.fill();continue;}const chosen=s.phase==='deploy'?u.id===picked:u.id===s.selectedTarget;ctx.fillStyle='#10211e60';ctx.beginPath();ctx.ellipse(q.x,q.y+32,32,10,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=chosen?'#f1d598':u.team==='ally'?'#8fc0b35c':'#d495705c';ctx.lineWidth=chosen?3:1;ctx.beginPath();ctx.ellipse(q.x,q.y+27,36,13,0,0,Math.PI*2);ctx.stroke();const bounce=s.phase==='battle'&&!paused?Math.sin(s.time*7+u.y)*2:0;if(u.shield>0){ctx.fillStyle='#74b8d32b';ctx.strokeStyle='#9bcfdf';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(q.x,q.y,43,55,0,0,Math.PI*2);ctx.fill();ctx.stroke();}{const c=cardOf(run,u.cardId);ctx.filter=cardFilters[u.cardId]||(Number.isInteger(c?.hue)?`hue-rotate(${c.hue}deg) saturate(1.28)`:'none');const img=imageFor(u.cardId,u.kind);if(img?.complete&&img.naturalWidth>0)ctx.drawImage(img,q.x-43,q.y-51+bounce,86,86);ctx.filter='none';}ctx.fillStyle='#12241d';ctx.fillRect(q.x-32,q.y-53,64,5);ctx.fillStyle=u.team==='ally'?'#a8c992':'#d39072';ctx.fillRect(q.x-32,q.y-53,64*Math.max(0,u.hp/u.max),5);ctx.fillStyle='#e3d8b2';ctx.font=(w<600?'20':'13')+'px sans-serif';ctx.textAlign='center';ctx.fillText((u.name||cardName(run,u.cardId)||names[u.kind])+(' '+ '★'.repeat(u.stars||1)),q.x,q.y+50);if((u.passive==='taunt'||Object.values(u.loadout||{}).some(id=>GEAR[id]?.effects?.taunt))&&u.team==='ally'){ctx.fillStyle='#f1d598';ctx.font='12px sans-serif';ctx.fillText('嘲讽',q.x,q.y-68);}if(u.stun>0){ctx.fillStyle='#f8db86';ctx.font='12px sans-serif';ctx.fillText('打断',q.x,q.y-82);}}
for(const e of s.effects){const p=map(e),fade=Math.max(0,Math.min(1,e.life));ctx.save();ctx.globalAlpha=fade;if(['fire','skill','cast','shield'].includes(e.type)){const r=18+(1.15-e.life)*58,grad=ctx.createRadialGradient(p.x,p.y,2,p.x,p.y,r);grad.addColorStop(0,e.type==='shield'?'#9be8ffcc':e.type==='fire'?'#ffd26acc':'#fff0aacc');grad.addColorStop(.45,e.type==='fire'?'#ef784866':'#7fc8ff44');grad.addColorStop(1,'#0000');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=e.type==='fire'?'#ffb45d':e.type==='shield'?'#9edcf2':'#f6d59a';ctx.lineWidth=e.type==='skill'?5:3;ctx.beginPath();ctx.arc(p.x,p.y,r*.62,0,Math.PI*2);ctx.stroke();}else if(e.type==='hit'){ctx.strokeStyle='#ffd28a';ctx.lineWidth=3;for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(p.x-24+i*16,p.y-18);ctx.lineTo(p.x-6+i*16,p.y+10);ctx.stroke();}}ctx.globalAlpha=Math.min(1,e.life*2);ctx.fillStyle=e.type==='death'?'#b9c5b6':'#ffe6a6';ctx.font='bold 15px sans-serif';ctx.fillText(e.text,p.x,p.y-15-(1-e.life)*18);ctx.restore();}ctx.globalAlpha=1;ctx.restore();}

const slotName=i=>`${i%2?'前':'后'}排${['上','中','下'][Math.floor(i/2)]}`;
function resize(){if(!canvas)return;const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw();}
let count=0;function frame(t){const dt=Math.min(.1,(t-last)/1000||0);last=t;if(!paused&&run.phase==='battle'){accumulator+=dt*speed;while(accumulator>=1/60&&run.phase==='battle'&&s.phase==='battle'){tick(s,1/60);accumulator-=1/60;saveTimer+=1/60;}if(++count%4===0||s.phase!=='battle')ui();draw();finish();if(saveTimer>=1){save();saveTimer=0;}}else accumulator=0;requestAnimationFrame(frame);}record.seen=[...new Set([...record.seen,...Object.keys(run.owned).filter(k=>run.owned[k]>0)])];shell();requestAnimationFrame(frame);
