export function create(){return {version:2,phase:'play',stage:0,time:0,player:{x:150,y:330,hp:100,feet:false,horn:false,attack:0,dash:0,invuln:0},animals:[{id:'rabbit',kind:'rabbit',x:290,y:370,hp:6,max:6,dead:false,windup:0},{id:'deer',kind:'deer',x:490,y:230,hp:18,max:18,dead:false,windup:0},{id:'boss',kind:'boss',x:850,y:325,hp:100,max:100,dead:false,windup:0,cooldown:2}],tree:{x:700,y:325,broken:false},fire:{x:865,y:470},effects:[],target:null,dashTime:0,message:'点击灵兔，靠近后自动吞噬',kills:0};}
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function note(s,text,x=s.player.x,y=s.player.y){s.message=text;s.effects.push({x,y,text,life:1.8});}
export function target(s,x,y){if(s.phase!=='play')return;const a=s.animals.find(a=>!a.dead&&distance(a,{x,y})<45);s.target=a?{id:a.id,x:a.x,y:a.y}:{x:Math.max(35,Math.min(965,x)),y:Math.max(65,Math.min(600,y))};}
export function dash(s){if(s.phase!=='play'||!s.player.horn||s.player.dash>0)return false;s.player.dash=2.5;s.dashTime=.32;s.player.invuln=.35;note(s,'冲撞！');return true;}
function move(body,x,y,step,s){let d=Math.hypot(x-body.x,y-body.y);if(d<1)return;const n=Math.min(step,d);let nx=body.x+(x-body.x)/d*n;let ny=body.y+(y-body.y)/d*n;
if(body.x<680&&nx>675&&(!s.tree.broken||Math.abs(ny-325)>85)){nx=675;if(s.dashTime>0&&s.player.horn&&Math.abs(ny-325)<85){s.tree.broken=true;s.stage=3;note(s,'山口已开 · 躲开红圈，狩猎穷奇',700,325);}}
body.x=Math.max(35,Math.min(965,nx));body.y=Math.max(65,Math.min(600,ny));}
export function tick(s,dt){if(s.phase!=='play')return;s.time+=dt;const p=s.player;p.attack=Math.max(0,p.attack-dt);p.dash=Math.max(0,p.dash-dt);p.invuln=Math.max(0,p.invuln-dt);s.dashTime=Math.max(0,s.dashTime-dt);s.effects=s.effects.filter(e=>(e.life-=dt)>0);
const tracked=s.animals.find(a=>a.id===s.target?.id&&!a.dead);if(tracked){s.target.x=tracked.x;s.target.y=tracked.y;}
if(s.target)move(p,s.target.x,s.target.y,(s.dashTime>0?650:p.feet?190:105)*dt,s);
for(const a of s.animals){if(a.dead)continue;let d=distance(p,a);
if(a.kind==='deer'&&d<180&&d>32){const vx=a.x-p.x,vy=a.y-p.y;let nx=a.x+vx/d*135*dt,ny=a.y+vy/d*135*dt;if(nx>625||nx<350||ny<100||ny>550){nx=a.x;ny=a.y+(a.y<325?1:-1)*135*dt;}a.x=Math.max(350,Math.min(625,nx));a.y=Math.max(100,Math.min(550,ny));}
if(a.kind==='boss'&&s.tree.broken){a.cooldown-=dt;if(a.windup>0){a.windup-=dt;if(a.windup<=0){if(distance(p,a.strike)<83&&p.invuln<=0){p.hp=Math.max(0,p.hp-22);note(s,'−22',p.x,p.y);}a.cooldown=1.6;a.strike=null;}}else if(d<130&&a.cooldown<=0){a.windup=.95;a.strike={x:p.x,y:p.y};}else if(d>62){move(a,p.x,p.y,72*dt,s);}if(distance(a,s.fire)<53){a.hp-=12*dt;if(Math.floor(s.time*2)!==a.fireTick){a.fireTick=Math.floor(s.time*2);s.effects.push({x:a.x,y:a.y,text:'灼烧',life:.6});}}}
d=distance(p,a);if(d<48&&p.attack<=0&&(a.kind!=='boss'||s.tree.broken)){const hit=s.dashTime>0?22:p.horn?10:6;a.hp-=hit;p.attack=.55;s.effects.push({x:a.x,y:a.y-15,text:'−'+hit,life:.6});}
if(a.hp<=0){a.hp=0;a.dead=true;s.kills++;p.hp=Math.min(100,p.hp+20);if(a.kind==='rabbit'){p.feet=true;s.stage=1;note(s,'长出疾足 · 现在追得上角鹿了');}if(a.kind==='deer'){p.horn=true;s.stage=2;note(s,'长出冲撞角 · 点击枯树，再按冲撞');}if(a.kind==='boss'){s.phase='won';s.target=null;note(s,'越过青岚 · 狩猎完成');}if(s.target?.id===a.id)s.target=null;}}
if(p.hp<=0){s.phase='lost';s.target=null;note(s,'归尘 · 留意穷奇落爪前的红圈');}}
export function restore(raw){try{const s=JSON.parse(raw);if(s.version!==2||!['play','won','lost'].includes(s.phase)||!Number.isFinite(s.time)||!s.player||!Array.isArray(s.animals)||s.animals.length!==3)return null;for(const b of [s.player,...s.animals])if(!Number.isFinite(b.x)||!Number.isFinite(b.y)||!Number.isFinite(b.hp)||b.x<0||b.x>1000||b.y<0||b.y>650||b.hp<0||b.hp>100)return null;for(const k of ['attack','dash','invuln'])if(!Number.isFinite(s.player[k]))return null;if(!s.tree||typeof s.tree.broken!=='boolean'||!s.fire||!Array.isArray(s.effects)||!Number.isFinite(s.dashTime))return null;if(s.animals.some((a,i)=>a.id!==['rabbit','deer','boss'][i]))return null;return s;}catch{return null;}}
