import {create,act,organs,sites,paths,intent,moves,restore} from './engine.mjs';
import {art} from './art.mjs';
const KEY='shiling.cards.v1';let warning='',state;try{state=restore(localStorage.getItem(KEY));}catch{warning='浏览器无法保存，本局刷新会丢失。';}state??=create();
const root=document.querySelector('#app');
const button=(label,action,value='',disabled=false,cls='')=>`<button class="${cls}" data-action="${action}" data-value="${value}" ${disabled?'disabled':''}>${label}</button>`;
const card=(name,picture,tag,text,action,value,extra='')=>`<button class="card ${extra}" data-action="${action}" data-value="${value}" draggable="${action==='visit'||action==='equip'}"><span class="card-tag">${tag}</span>${art(picture)}<strong>${name}</strong><span class="card-text">${text}</span><span class="card-foot">${action==='visit'?'点击前往 ↗':action==='equip'?'点击装配 ＋':'选择此牌 →'}</span></button>`;
function eventChoices(){switch(state.event){case 'rabbit':return button('吞噬 · 生命 +4 / 口粮 +2','choice','eat')+button('救治 · 药草 −1 / 获得伙伴','choice','save',!state.herbs);case 'herb':return button('就地疗伤 · 生命 +8','choice','heal')+button('采集 · 药草 +2','choice','take');case 'wolf':return button('狩猎 · 胜利获得器官','choice','fight')+button('潜行 · 口粮 +1 / 需要夜瞳','choice','sneak',!state.organs.includes('eye'));case 'shrine':return button('献血 · 生命 −5 / 选择器官','choice','offer',state.hp<=5);case 'forest':return button(`搜寻 · ${state.organs.includes('eye')?'夜瞳免伤':'生命 −3'} / 选择器官`,'choice','search');case 'fire':return button('歇息 · 口粮 −1 / 生命 +10','choice','rest',!state.food);}}
function board(){if(state.phase==='choose')return `<div class="section-title"><span>01 / 初生</span><h2>你将如何生存？</h2><p>选一枚器官。之后还能吞噬、替换，改变走法。</p></div><div class="cards">${['eye','armor','tail'].map(x=>card(organs[x].name,organs[x].art,{eye:'潜行',armor:'反击',tail:'伙伴'}[x],organs[x].text,'start',x)).join('')}</div>`;
if(state.phase==='map')return `<div class="section-title"><span>${state.step>=6?'终 / 山口':'探索 / '+(state.step+1)}</span><h2>${state.step>=6?'穷奇在等你':'下一步，去哪里？'}</h2><p>${state.step>=6?'装好器官，使用药草，然后迎战。':`选择一处，另外两处将错过 · ${state.food?'口粮 −1':'饥饿：生命 −3'}`}</p></div><div class="cards">${state.step>=6?card('穷奇','boss','最终强敌 · 40 生命','胜利后，留下一枚器官开启新生。','boss',''):paths(state).map(x=>card(sites[x].name,sites[x].art,sites[x].tag,sites[x].text,'visit',x)).join('')}</div>`;
if(state.phase==='event'){const e=sites[state.event];return `<div class="encounter">${art(e.art)}<div><span class="eyebrow">${e.tag}</span><h2>${e.name}</h2><p>${e.text}</p><div class="choices">${eventChoices()}${button('离开','choice','leave',false,'quiet')}</div></div></div>`;}
if(state.phase==='loot')return `<div class="section-title"><span>吞噬 / 进化</span><h2>${state.loot.length?'新的力量，新的代价':'这里已无可用器官'}</h2><p>选择一枚收入行囊，回到地图后装配。</p></div><div class="cards">${state.loot.map(x=>card(organs[x].name,organs[x].art,'器官',organs[x].text,'loot',x)).join('')}</div>${button('继续前行','skip','','','quiet')}`;
if(state.phase==='battle'){const e=state.enemy,i=intent(state);return `<div class="battle"><div class="enemy-art">${art(e.boss?'boss':'wolf')}</div><div class="enemy-info"><span class="eyebrow">${e.boss?'最终强敌':'遭遇战'} / 回合 ${state.turn+1}</span><h2>${e.name}</h2><div class="health"><i style="width:${e.hp/e.max*100}%"></i></div><p>${e.hp} / ${e.max} 生命</p><div class="intent"><b>下一步 · ${i.name}</b><span>${i.damage?`造成 ${i.damage} 伤害`:'正在准备重击，抓紧进攻'}</span></div><small>已备：格挡 ${state.block} · ${state.evade?'闪避生效':'无闪避'}</small></div></div><div class="hand-title"><b>灵力 ${'◆'.repeat(state.energy)}${'◇'.repeat(4-state.energy)}</b>${button('结束回合 →','end','','', 'primary')}</div><div class="hand">${moves(state).map(m=>`<button class="move" data-action="move" data-value="${m.id}" ${state.energy<m.cost?'disabled':''}><span>${m.cost} ◆</span><strong>${m.name}</strong><small>${m.text}</small></button>`).join('')}</div>`;}
return `<div class="ending">${art(state.phase==='won'?'shrine':'moon')}<span class="eyebrow">${state.phase==='won'?'此世 · 越山':'此世 · 归尘'}</span><h2>${state.phase==='won'?'山海记住了你的足迹':'万物归寂，再度初生'}</h2><p>${state.phase==='won'?'选择一枚已装备器官传承。下一世，你可以尝试另一种组合。':'这次的探索结束了。试试夜瞳闪避，或保留药草迎战。'}</p><div class="choices">${state.phase==='won'?state.organs.map(x=>button(`${state.legacy===x?'✓ ':''}传承${organs[x].name}`,'legacy',x)).join(''):''}${button('开启下一世 →','restart','','','primary')}</div></div>`;
}
function render(){root.innerHTML=`<header><a class="brand" href="./">食灵<span>列 传 / 山 海 牌 局</span></a><div class="chapter">青岚卷 <span>·</span> ${state.step}/6 遭遇</div>${button('重新开始','reset','','','quiet')}</header><main><aside class="character" data-drop="visit"><span class="eyebrow">你的异兽 / 初生灵狐</span><div class="avatar ${state.organs.includes('fire')?'fiery':''}">${art('fox')}${state.organs.map(x=>`<span class="mutation ${x}">${art(organs[x].art)}</span>`).join('')}</div><h1>${state.organs.includes('fire')?'烬尾':state.organs.includes('armor')?'玄鳞':state.organs.includes('eye')?'望夜':'青丘'}<span>灵狐</span></h1><div class="health"><i style="width:${state.hp/30*100}%"></i></div><div class="stats"><b>生命 ${state.hp}<small>/30</small></b><b>口粮 ${state.food}</b></div>${button(`药草 ${state.herbs} · 恢复 6`,'herb','',!['map','battle'].includes(state.phase)||!state.herbs||state.hp===30,'medicine')}<div class="organs" data-drop="equip"><div class="label">身体构筑 <span>${state.organs.length} / 3</span></div>${[0,1,2].map(i=>{const x=state.organs[i];return x?`<button class="slot" data-action="unequip" data-value="${x}" ${state.phase!=='map'?'disabled':''}>${art(organs[x].art)}<span><b>${organs[x].name}</b><small>${organs[x].text}</small></span><em>−</em></button>`:'<div class="slot empty">＋ 空器官槽</div>';}).join('')}<small>地图中点击卸下，点击行囊装配</small></div>${state.companion?'<div class="companion">'+art('rabbit')+'<span>灵兔同行<small>每回合协力 '+(state.organs.includes('tail')?4:2)+' 伤害</small></span></div>':''}</aside><section class="table"><div class="journey">${Array.from({length:7},(_,i)=>`<span class="${i<=state.step?'active':''}">${i===6?'终':i+1}</span>`).join('<i></i>')}</div>${board()}<div class="message" role="status">${state.message}</div></section></main><footer><div class="bag-label">行 囊<small>器官 ${state.bag.length}/6</small></div><div class="bag">${state.bag.length?state.bag.map(x=>card(organs[x].name,organs[x].art,'器官',organs[x].text,'equip',x,'mini')).join(''):'<p>狩猎与探索获得器官。最多装配三枚。</p>'}</div><span class="save">${warning||'本机自动存档<br>点击操作 · 也可拖动地点至灵狐、器官至身体槽'}</span></footer>`;}
function dispatch(action,value){if(action==='reset'&&!confirm('放弃当前牌局，重新开始？'))return;if(action==='restart'||action==='reset')state=create(Date.now(),action==='restart'?state.legacy:null);else if(action==='equip'&&state.phase==='map'&&state.organs.length>=3)state={...state,message:'身体槽已满。先点击左侧器官卸下，再装配新器官。'};else state=act(state,action,value);try{localStorage.setItem(KEY,JSON.stringify(state));}catch{warning='保存失败：本局进度只保留在当前页面。';}render();}
root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)dispatch(b.dataset.action,b.dataset.value);});
root.addEventListener('dragstart',e=>{const c=e.target.closest('[draggable="true"]');if(c)e.dataTransfer.setData('text/plain',JSON.stringify({action:c.dataset.action,value:c.dataset.value}));});
root.addEventListener('dragover',e=>{if(e.target.closest('[data-drop]'))e.preventDefault();});root.addEventListener('drop',e=>{const zone=e.target.closest('[data-drop]');if(!zone)return;e.preventDefault();try{const d=JSON.parse(e.dataTransfer.getData('text/plain'));if(d.action===zone.dataset.drop)dispatch(d.action,d.value);}catch{}});
window.addEventListener('storage',e=>{if(e.key===KEY){const next=restore(e.newValue);if(next){state=next;render();}}});render();
