import test from 'node:test';
import assert from 'node:assert/strict';
import {createBattle,start,tickAuto,skill,restoreBattle,battleReport,deploy} from './expedition-engine.mjs';
import {roster} from './progression.mjs';
const runOf=(owned)=>{const run={owned,round:1,level:1,phase:'battle'};run.formation=Array(6).fill(null);roster(run).slice(0,6).forEach((u,i)=>run.formation[i]=u.id);return run;};
const allies=s=>s.units.filter(u=>u.team==='ally');
const play=(s,n)=>{for(let i=0;i<n&&s.phase==='battle';i++)tickAuto(s,1/60);};
test('six slots set exact front/back positions and preserve separate copies',()=>{const run=runOf({turtle:2,bird:2,wolf:2}),s=createBattle(run);assert.equal(allies(s).length,6);assert.equal(new Set(allies(s).map(u=>u.id)).size,6);for(const u of allies(s)){assert.equal(u.x,u.slot%2?320:150);assert.equal(u.y,[130,280,430][Math.floor(u.slot/2)]);assert.equal(u.id,'a-'+run.formation[u.slot]);}assert.equal(Object.keys(s.skills).length,6);});
test('each duplicate has independent skill cooldown and damage attribution',()=>{for(const card of ['turtle','bird','wolf']){const s=createBattle(runOf({[card]:2}));start(s);for(const u of allies(s)){assert.equal(skill(s,u.id),true);assert.equal(s.stats.units[u.id].casts,1);assert(s.skills[u.id]>0);assert.equal(skill(s,u.id),false);}assert.doesNotThrow(()=>battleReport(s));}});
test('every duplicate bird and wolf participates in automatic casting',()=>{for(const card of ['bird','wolf']){const s=createBattle(runOf({[card]:2}));start(s);for(const u of allies(s))u.x=560;for(const e of s.units.filter(u=>u.team==='enemy')){e.hp=e.max=5000;e.cast=.5;e.strike={x:560,y:130};}play(s,180);for(const u of allies(s))assert(s.stats.units[u.id].casts>0);}});
test('duplicate turtles independently react after the previous shield ends',()=>{const s=createBattle(runOf({turtle:2}));start(s);for(const u of allies(s))u.shield=0;const [first,second]=allies(s),enemy=s.units.find(u=>u.team==='enemy');enemy.cast=.4;enemy.strike={x:first.x,y:first.y};tickAuto(s,1/60);assert.equal(s.stats.units[first.id].casts,1);for(const u of allies(s))u.shield=0;enemy.cast=.4;enemy.strike={x:second.x,y:second.y};tickAuto(s,1/60);assert.equal(s.stats.units[second.id].casts,1);});
test('a single animal needs no invented teammates and empty squads cannot start',()=>{for(const card of ['bird','wolf','turtle']){const s=createBattle(runOf({[card]:1}));assert.equal(allies(s).length,1);assert(start(s));assert.doesNotThrow(()=>{play(s,3700);battleReport(s);});}const empty=createBattle(runOf({}));assert.equal(start(empty),false);});
test('six-unit snapshot and multiple independent fire zones continue deterministically',()=>{const run=runOf({ember_bird:2,bird:2,wolf:2}),a=createBattle(run);start(a);for(const u of allies(a).filter(u=>u.cardId==='ember_bird'))skill(a,u.id);assert.equal(a.zones.length,2);const b=restoreBattle(JSON.parse(JSON.stringify(a)),run);assert(b);play(a,30);play(b,30);assert.deepEqual(b,a);});
test('legacy three-unit battle remaps ids, statistics, cooldowns and fire source',()=>{const legacy={owned:{turtle:1,ember_bird:1,wolf:1},equipped:{bird:'ember_bird'},phase:'battle'},a=createBattle(legacy);start(a);skill(a,'bird');const run=runOf(legacy.owned),b=restoreBattle(JSON.parse(JSON.stringify(a)),run);assert(b);const bird=allies(b).find(u=>u.kind==='bird');assert.equal(b.zones[0].sourceId,bird.id);assert.equal(b.stats.units[bird.id].casts,1);assert.equal(b.skills[bird.id],a.skills.bird);assert.equal(b.time,a.time);assert.equal(b.phase,'battle');assert.equal(bird.x,130);assert.doesNotThrow(()=>play(b,60));});

test('deployment swaps occupied cells and can move to any empty cell',()=>{const s=createBattle(runOf({turtle:1,bird:1})),[a,b]=allies(s);assert(deploy(s,a.id,1));assert.equal(a.slot,1);assert.equal(b.slot,0);assert(deploy(s,b.id,5));assert.equal(b.x,320);assert.equal(b.y,430);assert.equal(deploy(s,a.id,6),false);start(s);assert.equal(deploy(s,a.id,0),false);});
